spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myblog?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&serverTimezone=GMT%2B8
    username: ...
    password: ...
    hikari:
      max-lifetime: 500000
#  mail:
#    host: smtp.qq.com
#    username: qq@qq.com
#    # address: ...@qq.com
#    password: ...
#    default-encoding: utf-8
#    protocol: smtp
#    port: 25
  mail:
    host: smtp.qq.com
    username: qq@qq.com
    password: ...
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  level:
    root: info
    com.star: debug
  file:
    name: log/blog-dev.log


  redis:
    host: ...
    port: ...
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 5
        min-idle: 0
    password: root

#mybatis-plus配置控制台打印完整带参数SQL语句
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

spring.thymeleaf.content-type: text/html
spring.thymeleaf.cache: false
spring.thymeleaf.mode: LEGACYHTML5
